[project]
name = "fuelchain"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.access-control]
path = "contracts/access-control.clar"
depends_on = []

[contracts.fuel-inventory]
path = "contracts/fuel-inventory.clar"
depends_on = []

[contracts.fuel-token]
path = "contracts/fuel-token.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
